config/routes.rb
FreeAcc::Application.routes.draw do
  
  resources :categories

  resources :phrases
  resources :images do
    collection do
      get :search
    end
  end
  
  root :to => "words#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :words
  
  has_attached_file :picture, 
                    :styles => {:normal => "180x180"},
                    :storage => :s3, 
                    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
                    :path => "freeacc/:attachment/:style/:id.:extension"

end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  # GET /phrases
  # GET /phrases.xml
  def index
    @phrases = Phrase.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @phrases }
    end
  end

  # GET /phrases/1
  # GET /phrases/1.xml
  def show
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @phrase }
    end
  end

  # GET /phrases/new
  # GET /phrases/new.xml
  def new
    @phrase = Phrase.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @phrase }
    end
  end

  # GET /phrases/1/edit
  def edit
    @phrase = Phrase.find(params[:id])
  end

  # POST /phrases
  # POST /phrases.xml
  def create
    @phrase = Phrase.new(params[:phrase])

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to(@phrase, :notice => 'Phrase was successfully created.') }
        format.xml  { render :xml => @phrase, :status => :created, :location => @phrase }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @phrase.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /phrases/1
  # PUT /phrases/1.xml
  def update
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      if @phrase.update_attributes(params[:phrase])
        format.html { redirect_to(@phrase, :notice => 'Phrase was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @phrase.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.xml
  def destroy
    @phrase = Phrase.find(params[:id])
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to(phrases_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word_ids %><br />
    <%= f.text_field :word_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<h1>Listing phrases</h1>

<table>
  <tr>
    <th>Word ids</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phrases.each do |phrase| %>
  <tr>
    <td><%= phrase.word_ids %></td>
    <td><%= link_to 'Show', phrase %></td>
    <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
    <td><%= link_to 'Destroy', phrase, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word ids:</b>
  <%= @phrase.word_ids %>
</p>


<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>