config/routes.rb
FreeAcc::Application.routes.draw do
  
  resources :categories

  resources :phrases
  resources :images do
    collection do
      get :search
    end
  end
  
  root :to => "words#index"

end

app/models/word.rb
class Word < ActiveRecord::Base

  has_many :images, :order => 'vote_count DESC'
  
  has_many :phrase_words
  has_many :phrases, :through => :phrase_words
  
  validates_presence_of :english
  
  before_save :down_case_word
  
  def down_case_word
    self.english = self.english.downcase
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.xml
  
  before_filter :get_word
  
  def get_word
    @example_word = Word.find_by_english('toast')
  end
  
  def search
    @word = Word.find(:first, :conditions => ['english=?', params[:word].downcase])
    if !params[:word].blank? && !@word
      @word = Word.new
      @word.english = params[:word].downcase
    end
    render :action => 'new'
  end
  
  
  def index
    @words = Word.where('published=?', true)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @words }
    end
  end

  # GET /words/1
  # GET /words/1.xml
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/new
  # GET /words/new.xml
  def new
    @word = Word.new    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.xml
  def create
    @word = Word.new(params[:word])
  
      respond_to do |format|
        if @word.save
          format.html { redirect_to(word_images_path(@word), :notice => 'Word was successfully created.') }
          format.xml  { render :xml => @word, :status => :created, :location => @word }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
        end
      end
  end

  # PUT /words/1
  # PUT /words/1.xml
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to(word_images_path(@word), :notice => 'Word was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.xml
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to(words_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :english, :class => 'big_input'%>
  </div>

<h2>4) Terms And Conditions</h2>
<div class="content">
	<p>
		test
	</p>
</div>
<div class="field">
 <%= f.submit 'Submit', :disable_with => "Submitting..."%>
</div>

<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

app/views/words/index.html.erb
<% @words.each do |word| %>
	<%= image_tag word.images.first.picture(:small), :size => '100x100' %>
<% end %>

app/views/words/new.html.erb
<div id="contribute">
<h1>Contribute</h1>
	<p>
		Contributing to FreeACC.org as an artist is easy. By uploading images which express words and ideas you help others express themselves.
	</p>
<h2>1) What image/word do you want to contribute?</h2>
	<div class="content">
		<p>
			<%= form_tag(words_path, :method => :get) do %>
				<%= text_field_tag :word, params[:word], :class => 'big_input' %>
				<%= submit_tag 'Search', :disable_with => "Searching..."%>
			<% end %>
		</p>
	</div>
<h2>2) Review Word And Prior Submissions</h2>
<div class="content">
	<p>
		<ul>
			<li>Tip 1</li>
			<li>Tip 2</li>
			<li>Tip 3</li>
		</ul>
	</p>
</div>
<h2>3) Upload Your Image</h2>
<div class="content">
	<p>
		<%= render 'form' %>
	</p>
</div>
<h2>4) Terms And Conditions</h2>
<div class="content">
	<p>
		test
	</p>
</div>

</div>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<% if @word.images.blank? %>
	<h3>
		<span class="highlight">
			This word needs an image in order to be included in Free ACC
		</span>
	</h3>
<% end %>

<%= link_to "Add an image", new_word_image_path(@word)%>

<h1>
	<%=  @word.english  %>
</h1>
<%= link_to 'Edit', edit_word_path(@word) %>


<% @word.images.each do |image| %>
	test
<% end %>