config/routes.rb
FreeAcc::Application.routes.draw do
  
  resources :categories

  resources :phrases
  resources :images do
    collection do
      get :search
    end
  end
  
  root :to => "words#index"

end

app/models/image.rb
class Image < ActiveRecord::Base

  attr_accessor :terms_and_conditions

  belongs_to :category
  
  has_attached_file :picture, 
                    :styles => {:small => "125x125"},
                    :storage => :s3, 
                    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
                    :path => "freeacc/:attachment/:style/:id.:extension"

  validates_attachment_presence :picture
  
  validates_attachment_size :picture, :less_than => 500.kilobytes, :if => lambda { picture.dirty? }
  
  #Rails3 Bug, need to patch paperclip gem
  #validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png']
  
  validate :image_is_a_square
  
  def image_is_a_square
     dimensions = Paperclip::Geometry.from_file(self.picture.queued_for_write[:original])
     if !square(dimensions.width, dimensions.height)
       self.errors.add_to_base("Please upload a picture 400x400 pixels") 
     end
   end
   
   def square(width, height)
     if (350..440).include?(width) && (350..440).include?(height)
       true
     else
       false
     end
   end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def index
    @images = Image.find(:all)
  end
  
  def search
    if params[:word].blank?
      render :nothing => true
    else
      @images = Image.find(:all, :conditions => ['word like ?', "%#{params[:word]}%"])
      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @images = []
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @images = []
    @image = Image.new(params[:image])
    respond_to do |format|
      if @image.save
        format.html { redirect_to(images_path, :notice => "Your image was added. <a href='/images/new'>Add another image.</a>".html_safe) }
      else
        format.html { render :action => "new" }
      end
    end
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_errors.html.erb
<div id="error_explanation">

	<h2>
		<%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:
	</h2>

	<ul>
		<% @image.errors.full_messages.each do |msg| %>

			<li>
				<%= msg %>
			</li>

		<% end %>	
	</ul>

</div>

app/views/images/_form.html.erb
<div id="image_form">


<a name="/images/new#add_image"></a>

<div class="content">


	<div id='image_requirements'>
	

		<%= render 'errors', :f => f %>
	
		<h3>
			Image requirements
		</h3>
	
		<ul>
			<li>Is file is actually a picture (must be a .jpg, .png, .gif).</li>
			<li>Is your picture a square? If not it wont't get uploaded!</li>
			<li>Is your picture the right dimensions? (400x400px is the correct size).</li>
			<li>Is your picture the right size? (must be less than 400kb).</li>
		</ul>		
	
	</div>

  <div class="field">
    <%= f.file_field :picture %>
	<%= f.hidden_field :word %>
  </div>
</div>

</div>

app/views/images/_image.html.erb
<%= image_tag(image.picture(:small)) %>

app/views/images/_step_one.html.erb
<div class="content">

	<div id="word_form">
	
		<h3>
			Tips for your word and image.
		</h3>
	
		<ul>
			<li>
				Is it universal (will everyone understand)?
			</li>
			
			<li>
				Is it simple (will others understand it right away)?
			</li>
			
			<li>
				Is it appropriate for all ages? 
			</li>
		</ul>
	
		<div id="search_form">
		<%= form_tag(search_images_path, :method => :get, :remote => true) do %>
			<%= text_field_tag :word, params[:word] %> <%= submit_tag 'Search', :disable_with => "Searching..."%>
		<% end %>
		</div>
		
		<div id="images">
			<%= render @images %>
		</div>
		
	</div>
	
	<div id="links">
		<p>
			<%= link_to 'Add an image', "#", :id => 'add_image' %>
			
			<span id="current_word" class="highlight"></span>
			
			<%= link_to 'Change word', "#", :id => 'change_image' %>
		</p>
	</div>
	
</div>

app/views/images/_step_three.html.erb
<h2>
	3) Terms and conditions
</h2>
	
<div id="terms_and_conditions_div">

	<div class="content">
		
			<ul>
				<li>
					I understand this
				</li>
				
				<li>
					And that is this
				</li>
				
				<li>
					When here is there
				</li>
			</ul>

		  	<p>
				<%= f.check_box :terms_and_conditions %> <b>I accept the terms and conditions</b>
				<%= f.submit 'Submit', :disable_with => "Submitting..." %>
			</p>

	</div>

</div>

app/views/images/_step_two.html.erb
<h2>
	2) Add your image
</h2>
	
<div id="image_form">

	<div class="content">

		<div id='image_requirements'>
	
			<%= render 'errors', :f => f if @image.errors.any? %>
	
			<h3>
				Image requirements
			</h3>
	
			<ul>
				<li>
					Is the file actually a picture? (pictures usually end with .jpg, .png)
				</li>

				<li>
					Is your picture a square? If not it wont't upload!
				</li>
			
				<li>
					Is your picture the right dimensions? (400x400 pixels)
				</li>
			
				<li>
					Is your picture the right size? (must be less than 500 kb)
				</li>
			</ul>		
	
		</div>

	  <div class="field">
	
	    <%= f.file_field :picture %> <%= f.hidden_field :word %>

	  </div>

	</div>

</div>

app/views/images/_terms_and_conditions.html.erb
	<div id="terms_and_conditions_div">

	<div class="content">


			<ul>
				<li>I understand this</li>
				<li>And that is this</li>
				<li>When here is there</li>
			</ul>

		  	<p>
			<%= f.check_box :terms_and_conditions %> <b>I accept the terms and conditions</b> <%= f.submit 'Submit', :disable_with => "Submitting...", :disabled => true %>
			</p>

	</div>
</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div id="images" class="box-shadow">	
	<% @images.each do |img| %>
		<div id="<%= img.word%>" class="image">
			<%= image_tag(img.picture(:small))%> 
			<div><%= img.word %></div>
		</div>
	<% end %>
	<br style="clear:both;"/>
</div>

app/views/images/new.html.erb
<div id="contribute">

	<h1>
		Contribute
	</h1>

	<p>
		Contributing to FreeACC.org as an artist is easy. By uploading images which express words and ideas you help others express themselves.
	</p>

	<h2> 
		1) What is the word for the image you want to contribute?
	</h2>
	
	<%= render 'step_one' %>

	<%= form_for(@image, :html => {:multipart => true }) do |f| %>

		<%= render 'step_two', :f => f %>

		<%= render 'step_three', :f => f %>
		
	<% end %>
	
</div>

app/views/images/search.js.erb
var word = '<%= params[:word] %>';

$("#image_word").val("<%= params[:word] %>");
$("#add_image").show();

// Populate #images div with appropiate response //

<% if @images.blank? %>
	$("#images").append("<p>Looks like no images have been added for <span class='highlight'> "+ word +" </span></p>");
<% else %>
	$("#images").html("<p><%= escape_javascript(render(@images)) %></p>");
	$("#images").append("<p>Does your picture represent <b><%= params[:word]%></b> better than the latter pictures? If so go ahead and add an image.</p>");
<% end %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>